# Generated by Django 5.0.14 on 2026-01-05 22:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(help_text='Short description for project card (1-2 sentences)')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list for card badges', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('challenge', wagtail.fields.RichTextField(blank=True, help_text='The problem or need that was addressed')),
                ('solution', wagtail.fields.RichTextField(blank=True, help_text='How the project solved the challenge')),
                ('details', wagtail.fields.RichTextField(blank=True, help_text='Technical implementation details')),
                ('diagram_caption', models.CharField(blank=True, max_length=300)),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('code_snippet', models.TextField(blank=True, help_text='Optional code sample')),
                ('code_language', models.CharField(blank=True, help_text="e.g., 'python', 'yaml', 'bash'", max_length=50)),
                ('diagram', models.ForeignKey(blank=True, help_text='Architecture or flow diagram', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Image shown on project card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project Page',
                'ordering': ['order'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
